#string operations


In [15]:
import tensorflow as tf
sess = tf.Session()
hello = tf.constant("hello")
world = tf.constant("world")
helloworld = tf.add(hello,world)
print(sess.run(helloworld))

b'helloworld'


#placeholder with float value & dict

In [16]:
a = tf.placeholder(tf.float32)
b = a*2
res = sess.run(b, feed_dict = {a:3})
print(res)

6.0


#feeding placeholder with vector rank 1

In [17]:
res = sess.run(b, feed_dict ={a:[3,4,5]})
print(res)

[ 6.  8. 10.]


#feeding placeholder with multidimesional vector

In [18]:
dictionary = {a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}
res = sess.run(b,feed_dict = dictionary)
print(res)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [20]:
sess.close()

#common syntax for creating session


In [21]:
with tf.Session() as sess:
    res = sess.run(hello+world)
    print(res)

b'helloworld'


#checking for session 

In [22]:
sess.run(a)

RuntimeError: Attempted to use a closed Session.